#!/bin/bash
# This script allows to source FCCSW stack for a given release and platform.
# variables $RELEASE and $PLATFORM have to be exported before source this script by swan_env
# This stack in particlar has an extra folder with an id generated by spack, in a similar way 
# they are doing in /cvmfs/fcc.cern.ch/sw/latest/setup.sh we put the regular expression "*" to complete the path. 
source /cvmfs/sw.hsf.org/spackages2/key4hep-stack/$RELEASE/$PLATFORM/*/setup.sh
